In [1]:
data=[]
for i in [0,1]:
    for j in [0,1]:
        x=[i,j]
        data.append(x)
print(data)

[[0, 0], [0, 1], [1, 0], [1, 1]]


In [2]:
import numpy as np

# and 

In [3]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [4]:
def sigmoid_derivative(x):
    return sigmoid(x)*(1-sigmoid(x))

In [5]:
out=[0,0,0,1] # and gate

input_weights= np.random.uniform(size=(2,4)) # 2 inputs, 4 outputs
hidden_weights= np.random.uniform(size=(4,1)) # 4 inputs, 1 output
input_bias= np.random.uniform(size=(1,4)) # 1 input, 4 outputs
hidden_bias= np.random.uniform(size=(1,1)) # 1 input, 1
lr=0.1 # learning rate
print(input_weights) 
print(hidden_weights)
print(input_bias)
print(hidden_bias)
print("-----")



[[0.96209364 0.06425972 0.96501614 0.055493  ]
 [0.54972631 0.56193694 0.70476401 0.48142117]]
[[0.24713716]
 [0.2400731 ]
 [0.91631196]
 [0.1159    ]]
[[0.09324444 0.77987466 0.86039249 0.63770824]]
[[0.74279748]]
-----


In [6]:
def forward_pass(inputs):
    hidden_layer = sigmoid(np.dot(inputs, input_weights) + input_bias)
    output_layer = sigmoid(np.dot(hidden_layer, hidden_weights) + hidden_bias)
    return hidden_layer, output_layer


In [7]:
y_preds=[]
for i, x in enumerate(data):
    hidden_layer, output_layer = forward_pass(x)
    y_preds.append(output_layer)
    print(f"Input: {x}, Output: {output_layer} , hidden: {hidden_layer}, expected: {out[i]}")

Input: [0, 0], Output: [[0.85276915]] , hidden: [[0.52329423 0.6856531  0.70274265 0.65423522]], expected: 0
Input: [0, 1], Output: [[0.87439028]] , hidden: [[0.65542469 0.7927877  0.82709203 0.7538272 ]], expected: 0
Input: [1, 0], Output: [[0.8765788]] , hidden: [[0.74179864 0.69933525 0.86121385 0.66667868]], expected: 0
Input: [1, 1], Output: [[0.8888126]] , hidden: [[0.83272501 0.80314555 0.92623015 0.76397952]], expected: 1


In [8]:
def error(y_true, y_pred):
    eps = 1e-15  # small constant to avoid log(0)
    y_pred = np.clip(y_pred, eps, 1 - eps)  # clip predictions to avoid log(0)
    return np.mean(-(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred)))

In [9]:
print("-----")
print("Error:", error(np.array(out), np.array(y_preds).flatten()))

-----
Error: 1.550087595214401
