In [1]:
data=[]
for i in [0,1]:
    for j in [0,1]:
        x=[i,j]
        data.append(x)
print(data)

[[0, 0], [0, 1], [1, 0], [1, 1]]


In [2]:
import numpy as np

# and 

In [3]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [4]:
def sigmoid_derivative(x):
    return sigmoid(x)*(1-sigmoid(x))

In [5]:
out=[0,0,0,1] # and gate

input_weights= np.random.uniform(size=(2,4)) # 2 inputs, 4 outputs
hidden_weights= np.random.uniform(size=(4,1)) # 4 inputs, 1 output
input_bias= np.random.uniform(size=(1,4)) # 1 input, 4 outputs
hidden_bias= np.random.uniform(size=(1,1)) # 1 input, 1
lr=0.1 # learning rate
print(input_weights) 
print(hidden_weights)
print(input_bias)
print(hidden_bias)
print("-----")



[[0.38273512 0.58952921 0.56137466 0.75021024]
 [0.62558086 0.39059046 0.74569151 0.13594989]]
[[0.93850629]
 [0.97232854]
 [0.22484539]
 [0.67561096]]
[[0.50113482 0.51187698 0.65129776 0.44889341]]
[[0.97588518]]
-----


In [6]:
def forward_pass(inputs):
    hidden_layer = sigmoid(np.dot(inputs, input_weights) + input_bias)
    output_layer = sigmoid(np.dot(hidden_layer, hidden_weights) + hidden_bias)
    return hidden_layer, output_layer


In [9]:
for i, x in enumerate(data):
    hidden_layer, output_layer = forward_pass(x)
    print(f"Input: {x}, Output: {output_layer} , hidden: {hidden_layer}, expected: {out[i]}")

Input: [0, 0], Output: [[0.93868357]] , hidden: [[0.62272598 0.62524638 0.65730285 0.6103761 ]], expected: 0
Input: [0, 1], Output: [[0.95214625]] , hidden: [[0.75523228 0.7114563  0.8017057  0.64218109]], expected: 0
Input: [1, 0], Output: [[0.95530505]] , hidden: [[0.70762353 0.75052349 0.77077146 0.76836529]], expected: 0
Input: [1, 1], Output: [[0.9633922]] , hidden: [[0.8189798  0.81637777 0.87635578 0.79167532]], expected: 1


In [8]:
print(sigmoid(1))

0.7310585786300049
