In [5]:
import random as rd
import numpy as np

In [6]:
data = [[0,0],[0,1],[1,0],[1,1]]
out =[0,1,1,0]
hidd =[[rd.uniform(-1,1),rd.uniform(-1,1),rd.uniform(-1,1)],[rd.uniform(-1,1),rd.uniform(-1,1),rd.uniform(-1,1)]]
ol=[[rd.uniform(-1,1),rd.uniform(-1,1),rd.uniform(-1,1)]]
hidd = np.array(hidd)
ol=np.array(ol)
print(hidd)
print(ol)
print(hidd.shape)
print(ol.shape)

[[ 0.94316114 -0.92145147  0.79212578]
 [ 0.22684927 -0.3275398  -0.96780329]]
[[-0.57136813  0.29027855  0.68054584]]
(2, 3)
(1, 3)


In [7]:
r=np.dot(data[3],hidd)
print(r)
print(r.shape)
print("inp to l1")

[ 1.17001041 -1.24899127 -0.17567751]
(3,)
inp to l1
